#!/usr/bin/env python3
"""Export shared TypeScript types from Pydantic enums and core schemas."""

from __future__ import annotations

from pathlib import Path

from jober_schemas.enums import (
    AttemptStatus,
    CheckpointStatus,
    CheckpointType,
    DocumentType,
    FieldObservationStatus,
    JobTargetStatus,
    RunPolicy,
    RunStatus,
)

OUT = Path(__file__).resolve().parents[1] / "generated" / "types.ts"


def _ts_enum(name: str, enum_cls: type) -> str:
    members = " | ".join(f'"{m.value}"' for m in enum_cls)
    return f"export type {name} = {members};\n"


def main() -> None:
    lines = [
        "// Auto-generated by packages/schemas/scripts/export_typescript.py — do not edit.\n",
        _ts_enum("RunStatus", RunStatus),
        _ts_enum("RunPolicy", RunPolicy),
        _ts_enum("AttemptStatus", AttemptStatus),
        _ts_enum("FieldObservationStatus", FieldObservationStatus),
        _ts_enum("CheckpointType", CheckpointType),
        _ts_enum("CheckpointStatus", CheckpointStatus),
        _ts_enum("DocumentType", DocumentType),
        _ts_enum("JobTargetStatus", JobTargetStatus),
        "\nexport interface JobTargetRead {\n"
        "  id: string;\n"
        "  created_at: string;\n"
        "  updated_at: string;\n"
        "  company: string;\n"
        "  role: string;\n"
        "  status: JobTargetStatus;\n"
        "  rank?: number | null;\n"
        "  priority?: string | null;\n"
        "  fit_lane?: string | null;\n"
        "  why_fit?: string | null;\n"
        "  cover_letter_hook?: string | null;\n"
        "  stage_signal?: string | null;\n"
        "  location_work_style?: string | null;\n"
        "  direct_apply_url?: string | null;\n"
        "  company_careers_url?: string | null;\n"
        "  applied_date?: string | null;\n"
        "  follow_up_date?: string | null;\n"
        "  notes?: string | null;\n"
        "  ats_guess?: string | null;\n"
        "  needs_url?: boolean;\n"
        "}\n"
        "\nexport interface PlatformDetectionRead {\n"
        "  platform: string;\n"
        "  confidence: number;\n"
        "  evidence: string[];\n"
        "}\n"
        "\nexport interface JobProfileRead {\n"
        "  title: string;\n"
        "  company: string;\n"
        "  location?: string | null;\n"
        "  description: string;\n"
        "  responsibilities: string[];\n"
        "  requirements: string[];\n"
        "  seniority_signal?: string | null;\n"
        "  keywords: string[];\n"
        "  fit_score?: number | null;\n"
        "  company_product_summary?: string | null;\n"
        "}\n"
        "\nexport interface JobExtractionRead {\n"
        "  id: string;\n"
        "  created_at: string;\n"
        "  updated_at: string;\n"
        "  job_target_id: string;\n"
        "  platform_detection: PlatformDetectionRead;\n"
        "  job_profile: JobProfileRead;\n"
        "  cached: boolean;\n"
        "  extracted_at: string | null;\n"
        "  run_id?: string | null;\n"
        "}\n"
        "\nexport interface ImportWarningRead {\n"
        "  sheet: string;\n"
        "  row: number | null;\n"
        "  code: string;\n"
        "  message: string;\n"
        "}\n"
        "\nexport interface EntityImportStatsRead {\n"
        "  created: number;\n"
        "  updated: number;\n"
        "  skipped: number;\n"
        "}\n"
        "\nexport interface ColumnMappingPreview {\n"
        "  field: string;\n"
        "  matched_header: string | null;\n"
        "  confidence: number;\n"
        "  required: boolean;\n"
        "}\n"
        "\nexport interface ImportReportRead {\n"
        "  import_id: string;\n"
        "  dry_run: boolean;\n"
        "  mappings: Record<string, ColumnMappingPreview[]>;\n"
        "  metadata_sheets: string[];\n"
        "  job_targets: EntityImportStatsRead;\n"
        "  company_boards: EntityImportStatsRead;\n"
        "  cover_letter_angles: EntityImportStatsRead;\n"
        "  warnings: ImportWarningRead[];\n"
        "}\n",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
