#!/usr/bin/env python3
"""Export shared TypeScript types from Pydantic enums and core schemas."""

from __future__ import annotations

from pathlib import Path

from jober_schemas.enums import (
    AttemptStatus,
    CheckpointStatus,
    CheckpointType,
    DocumentType,
    FieldObservationStatus,
    JobTargetStatus,
    RunPolicy,
    RunStatus,
)

OUT = Path(__file__).resolve().parents[1] / "generated" / "types.ts"


def _ts_enum(name: str, enum_cls: type) -> str:
    members = " | ".join(f'"{m.value}"' for m in enum_cls)
    return f"export type {name} = {members};\n"


def main() -> None:
    lines = [
        "// Auto-generated by packages/schemas/scripts/export_typescript.py — do not edit.\n",
        _ts_enum("RunStatus", RunStatus),
        _ts_enum("RunPolicy", RunPolicy),
        _ts_enum("AttemptStatus", AttemptStatus),
        _ts_enum("FieldObservationStatus", FieldObservationStatus),
        _ts_enum("CheckpointType", CheckpointType),
        _ts_enum("CheckpointStatus", CheckpointStatus),
        _ts_enum("DocumentType", DocumentType),
        _ts_enum("JobTargetStatus", JobTargetStatus),
        "\nexport interface JobTargetRead {\n"
        "  id: string;\n"
        "  company: string;\n"
        "  role: string;\n"
        "  status: JobTargetStatus;\n"
        "  priority?: string | null;\n"
        "  fit_lane?: string | null;\n"
        "  direct_apply_url?: string | null;\n"
        "  applied_date?: string | null;\n"
        "  follow_up_date?: string | null;\n"
        "}\n",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
