"""initial schema

Revision ID: 42c29075a206
Revises: 
Create Date: 2026-06-06 04:16:54.070924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42c29075a206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_boards',
    sa.Column('priority', sa.String(length=8), nullable=True),
    sa.Column('company_board', sa.String(length=255), nullable=False),
    sa.Column('representative_roles', sa.Text(), nullable=True),
    sa.Column('stage_signal', sa.String(length=255), nullable=True),
    sa.Column('why_save', sa.Text(), nullable=True),
    sa.Column('company_careers_url', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cover_letter_angles',
    sa.Column('use_case', sa.String(length=255), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_targets',
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('fit_lane', sa.String(length=128), nullable=True),
    sa.Column('stage_signal', sa.String(length=255), nullable=True),
    sa.Column('location_work_style', sa.String(length=255), nullable=True),
    sa.Column('why_fit', sa.Text(), nullable=True),
    sa.Column('cover_letter_hook', sa.Text(), nullable=True),
    sa.Column('public_contact', sa.String(length=320), nullable=True),
    sa.Column('direct_apply_url', sa.Text(), nullable=True),
    sa.Column('company_careers_url', sa.Text(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('import_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_targets_status', 'job_targets', ['status'], unique=False)
    op.create_table('resume_assets',
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('skills_index', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_runs',
    sa.Column('job_target_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.String(length=32), nullable=True),
    sa.Column('policy', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('browser_session_id', sa.String(length=128), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('submission_confirmation_text', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('human_review_required_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_target_id'], ['job_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_runs_status', 'application_runs', ['status'], unique=False)
    op.create_table('user_profiles',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_authorization', sa.Text(), nullable=True),
    sa.Column('relocation_pref', sa.Boolean(), nullable=True),
    sa.Column('onsite_pref', sa.Boolean(), nullable=True),
    sa.Column('hybrid_pref', sa.Boolean(), nullable=True),
    sa.Column('salary_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitive_eeo_answers', sa.LargeBinary(), nullable=True),
    sa.Column('default_resume_asset_id', sa.UUID(), nullable=True),
    sa.Column('cover_letter_style_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_completeness_score', sa.Float(), nullable=True),
    sa.Column('field_consent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_resume_asset_id'], ['resume_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_attempts',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('platform_detected', sa.String(length=64), nullable=True),
    sa.Column('strategy_name', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_object_key', sa.String(length=512), nullable=True),
    sa.Column('video_object_key', sa.String(length=512), nullable=True),
    sa.Column('final_screenshot_object_key', sa.String(length=512), nullable=True),
    sa.Column('dom_snapshot_object_key', sa.String(length=512), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_documents',
    sa.Column('job_target_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('object_key_pdf', sa.String(length=512), nullable=True),
    sa.Column('object_key_docx', sa.String(length=512), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('keyword_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_target_id'], ['job_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_checkpoints',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('agent_role', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('redacted_prompt', sa.Text(), nullable=True),
    sa.Column('redacted_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('browser_events',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('selector', sa.String(length=512), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('screenshot_key', sa.String(length=512), nullable=True),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['application_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_browser_events_attempt_id', 'browser_events', ['attempt_id'], unique=False)
    op.create_table('form_field_observations',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('field_type', sa.String(length=64), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapped_profile_field', sa.String(length=128), nullable=True),
    sa.Column('proposed_value_redacted', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['application_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up legacy PG enum types from earlier migration attempts.
    for enum_name in (
        "jobtargetstatus",
        "runstatus",
        "runpolicy",
        "attemptstatus",
        "documenttype",
        "checkpointtype",
        "checkpointstatus",
        "fieldobservationstatus",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))

    op.drop_table('form_field_observations')
    op.drop_index('ix_browser_events_attempt_id', table_name='browser_events')
    op.drop_table('browser_events')
    op.drop_table('llm_calls')
    op.drop_table('human_checkpoints')
    op.drop_table('generated_documents')
    op.drop_table('application_attempts')
    op.drop_table('user_profiles')
    op.drop_index('ix_application_runs_status', table_name='application_runs')
    op.drop_table('application_runs')
    op.drop_table('resume_assets')
    op.drop_index('ix_job_targets_status', table_name='job_targets')
    op.drop_table('job_targets')
    op.drop_table('cover_letter_angles')
    op.drop_table('company_boards')
    # ### end Alembic commands ###
